# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_gasList.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_gasList(object):
    def setupUi(self, Index_gasList):
        Index_gasList.setObjectName("Index_gasList")
        Index_gasList.resize(807, 471)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/23.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index_gasList.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Index_gasList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Index_gasList)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refreshButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton)
        self.deleteButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Index_gasList)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chartView = QChartView(self.frame)
        self.chartView.setObjectName("chartView")
        self.verticalLayout_2.addWidget(self.chartView)
        self.horizontalLayout_3.addWidget(self.frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.maxEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.maxEdit.setReadOnly(True)
        self.maxEdit.setObjectName("maxEdit")
        self.gridLayout.addWidget(self.maxEdit, 3, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.timeEdit = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.timeEdit.setFont(font)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 1, 4, 1, 1)
        self.extrEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.extrEdit.setReadOnly(True)
        self.extrEdit.setObjectName("extrEdit")
        self.gridLayout.addWidget(self.extrEdit, 5, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.minEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.minEdit.setReadOnly(True)
        self.minEdit.setObjectName("minEdit")
        self.gridLayout.addWidget(self.minEdit, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.oriEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.oriEdit.setReadOnly(True)
        self.oriEdit.setObjectName("oriEdit")
        self.gridLayout.addWidget(self.oriEdit, 2, 4, 1, 1)
        self.sensorBox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sensorBox.setFont(font)
        self.sensorBox.setObjectName("sensorBox")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.sensorBox.addItem("")
        self.gridLayout.addWidget(self.sensorBox, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)

        self.retranslateUi(Index_gasList)
        QtCore.QMetaObject.connectSlotsByName(Index_gasList)

    def retranslateUi(self, Index_gasList):
        _translate = QtCore.QCoreApplication.translate
        Index_gasList.setWindowTitle(_translate("Index_gasList", "Dialog"))
        self.groupBox.setTitle(_translate("Index_gasList", "气体列表"))
        self.refreshButton.setText(_translate("Index_gasList", "刷新列表"))
        self.deleteButton.setText(_translate("Index_gasList", "删除"))
        self.groupBox_2.setTitle(_translate("Index_gasList", "详细信息"))
        self.label_4.setText(_translate("Index_gasList", "最小值"))
        self.label_2.setText(_translate("Index_gasList", "初始值"))
        self.label_3.setText(_translate("Index_gasList", "最大值"))
        self.label.setText(_translate("Index_gasList", "采集次数"))
        self.label_5.setText(_translate("Index_gasList", "极值点"))
        self.sensorBox.setItemText(0, _translate("Index_gasList", "传感器1"))
        self.sensorBox.setItemText(1, _translate("Index_gasList", "传感器2"))
        self.sensorBox.setItemText(2, _translate("Index_gasList", "传感器3"))
        self.sensorBox.setItemText(3, _translate("Index_gasList", "传感器4"))
        self.sensorBox.setItemText(4, _translate("Index_gasList", "传感器5"))
        self.sensorBox.setItemText(5, _translate("Index_gasList", "传感器6"))
        self.sensorBox.setItemText(6, _translate("Index_gasList", "传感器7"))
        self.sensorBox.setItemText(7, _translate("Index_gasList", "传感器8"))
        self.sensorBox.setItemText(8, _translate("Index_gasList", "传感器9"))
        self.sensorBox.setItemText(9, _translate("Index_gasList", "传感器10"))
        self.sensorBox.setItemText(10, _translate("Index_gasList", "传感器11"))
        self.sensorBox.setItemText(11, _translate("Index_gasList", "传感器12"))
        self.sensorBox.setItemText(12, _translate("Index_gasList", "传感器13"))
        self.sensorBox.setItemText(13, _translate("Index_gasList", "传感器14"))
        self.sensorBox.setItemText(14, _translate("Index_gasList", "传感器15"))
        self.label_6.setText(_translate("Index_gasList", "Sensor:"))
from QChartView import QChartView
import res_Index_rc
