# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_gasAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_gasAnalysis(object):
    def setupUi(self, Index_gasAnalysis):
        Index_gasAnalysis.setObjectName("Index_gasAnalysis")
        Index_gasAnalysis.resize(679, 424)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index_gasAnalysis.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Index_gasAnalysis)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Index_gasAnalysis)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Index_gasAnalysis)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LogisticBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.LogisticBox.setFont(font)
        self.LogisticBox.setObjectName("LogisticBox")
        self.verticalLayout_2.addWidget(self.LogisticBox)
        self.SVCBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SVCBox.setFont(font)
        self.SVCBox.setObjectName("SVCBox")
        self.verticalLayout_2.addWidget(self.SVCBox)
        self.PerceptronBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PerceptronBox.setFont(font)
        self.PerceptronBox.setObjectName("PerceptronBox")
        self.verticalLayout_2.addWidget(self.PerceptronBox)
        self.kNNBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kNNBox.setFont(font)
        self.kNNBox.setObjectName("kNNBox")
        self.verticalLayout_2.addWidget(self.kNNBox)
        self.ForestBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ForestBox.setFont(font)
        self.ForestBox.setObjectName("ForestBox")
        self.verticalLayout_2.addWidget(self.ForestBox)
        self.gaussianBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gaussianBox.setFont(font)
        self.gaussianBox.setObjectName("gaussianBox")
        self.verticalLayout_2.addWidget(self.gaussianBox)
        self.Linear_SVCBox = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Linear_SVCBox.setFont(font)
        self.Linear_SVCBox.setObjectName("Linear_SVCBox")
        self.verticalLayout_2.addWidget(self.Linear_SVCBox)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Index_gasAnalysis)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.typeBox = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.typeBox.setFont(font)
        self.typeBox.setObjectName("typeBox")
        self.typeBox.addItem("")
        self.horizontalLayout_3.addWidget(self.typeBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameEdit = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameEdit.setFont(font)
        self.nameEdit.setMaxLength(10)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_2.addWidget(self.nameEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.OKButton = QtWidgets.QPushButton(self.groupBox_3)
        self.OKButton.setObjectName("OKButton")
        self.verticalLayout_3.addWidget(self.OKButton)
        self.verticalLayout_3.setStretch(2, 2)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(Index_gasAnalysis)
        QtCore.QMetaObject.connectSlotsByName(Index_gasAnalysis)

    def retranslateUi(self, Index_gasAnalysis):
        _translate = QtCore.QCoreApplication.translate
        Index_gasAnalysis.setWindowTitle(_translate("Index_gasAnalysis", "Dialog"))
        self.groupBox.setTitle(_translate("Index_gasAnalysis", "Step1 选择气体数据 "))
        self.groupBox_2.setTitle(_translate("Index_gasAnalysis", "Step2 选择分类器"))
        self.LogisticBox.setText(_translate("Index_gasAnalysis", "逻辑回归"))
        self.SVCBox.setText(_translate("Index_gasAnalysis", "支持向量机"))
        self.PerceptronBox.setText(_translate("Index_gasAnalysis", "感知机"))
        self.kNNBox.setText(_translate("Index_gasAnalysis", "kNN聚类"))
        self.ForestBox.setText(_translate("Index_gasAnalysis", "随机森林"))
        self.gaussianBox.setText(_translate("Index_gasAnalysis", "朴素贝叶斯"))
        self.Linear_SVCBox.setText(_translate("Index_gasAnalysis", "线性支持向量机"))
        self.groupBox_3.setTitle(_translate("Index_gasAnalysis", "Step3 命名并确认"))
        self.label_2.setText(_translate("Index_gasAnalysis", "类别"))
        self.typeBox.setItemText(0, _translate("Index_gasAnalysis", "呼气者性别"))
        self.label.setText(_translate("Index_gasAnalysis", "命名"))
        self.OKButton.setText(_translate("Index_gasAnalysis", "确认"))
import res_Index_rc
