# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_statusInfo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_statusInfo(object):
    def setupUi(self, Index_statusInfo):
        Index_statusInfo.setObjectName("Index_statusInfo")
        Index_statusInfo.resize(703, 457)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/147.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index_statusInfo.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Index_statusInfo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Index_statusInfo)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.refreshButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_3.addWidget(self.refreshButton)
        self.deleteButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_3.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Index_statusInfo)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.saveTimeEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.saveTimeEdit.setReadOnly(True)
        self.saveTimeEdit.setObjectName("saveTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.saveTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.preTypeEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.preTypeEdit.setReadOnly(True)
        self.preTypeEdit.setObjectName("preTypeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.preTypeEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.preKNNEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.preKNNEdit.setReadOnly(True)
        self.preKNNEdit.setObjectName("preKNNEdit")
        self.gridLayout.addWidget(self.preKNNEdit, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.preLogisticEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.preLogisticEdit.setReadOnly(True)
        self.preLogisticEdit.setObjectName("preLogisticEdit")
        self.gridLayout.addWidget(self.preLogisticEdit, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.prePerceptronEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.prePerceptronEdit.setReadOnly(True)
        self.prePerceptronEdit.setObjectName("prePerceptronEdit")
        self.gridLayout.addWidget(self.prePerceptronEdit, 2, 2, 1, 1)
        self.preGaussianEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.preGaussianEdit.setReadOnly(True)
        self.preGaussianEdit.setObjectName("preGaussianEdit")
        self.gridLayout.addWidget(self.preGaussianEdit, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.preSVCEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.preSVCEdit.setReadOnly(True)
        self.preSVCEdit.setObjectName("preSVCEdit")
        self.gridLayout.addWidget(self.preSVCEdit, 1, 2, 1, 1)
        self.preForestEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.preForestEdit.setReadOnly(True)
        self.preForestEdit.setObjectName("preForestEdit")
        self.gridLayout.addWidget(self.preForestEdit, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.preLinearSVCEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.preLinearSVCEdit.setReadOnly(True)
        self.preLinearSVCEdit.setObjectName("preLinearSVCEdit")
        self.gridLayout.addWidget(self.preLinearSVCEdit, 6, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.preVoteEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.preVoteEdit.setReadOnly(True)
        self.preVoteEdit.setObjectName("preVoteEdit")
        self.horizontalLayout_2.addWidget(self.preVoteEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(Index_statusInfo)
        QtCore.QMetaObject.connectSlotsByName(Index_statusInfo)

    def retranslateUi(self, Index_statusInfo):
        _translate = QtCore.QCoreApplication.translate
        Index_statusInfo.setWindowTitle(_translate("Index_statusInfo", "Dialog"))
        self.groupBox.setTitle(_translate("Index_statusInfo", "分析记录列表"))
        self.refreshButton.setText(_translate("Index_statusInfo", "刷新列表"))
        self.deleteButton.setText(_translate("Index_statusInfo", "删除记录"))
        self.groupBox_2.setTitle(_translate("Index_statusInfo", "分析结果"))
        self.label.setText(_translate("Index_statusInfo", "气体保存时间"))
        self.label_2.setText(_translate("Index_statusInfo", "分析类别"))
        self.groupBox_3.setTitle(_translate("Index_statusInfo", "分类器预测结果"))
        self.label_5.setText(_translate("Index_statusInfo", "感知机"))
        self.label_6.setText(_translate("Index_statusInfo", "kNN聚类"))
        self.label_7.setText(_translate("Index_statusInfo", "随机森林"))
        self.label_4.setText(_translate("Index_statusInfo", "支持向量机"))
        self.label_8.setText(_translate("Index_statusInfo", "朴素贝叶斯"))
        self.label_3.setText(_translate("Index_statusInfo", "逻辑回归"))
        self.label_9.setText(_translate("Index_statusInfo", "线性支持向量机"))
        self.label_10.setText(_translate("Index_statusInfo", "投票法综合预测:"))
import res_Index_rc
