# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_passwordCh.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_passwordCh(object):
    def setupUi(self, Index_passwordCh):
        Index_passwordCh.setObjectName("Index_passwordCh")
        Index_passwordCh.resize(840, 446)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/21.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index_passwordCh.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Index_passwordCh)
        self.gridLayout.setContentsMargins(40, -1, 40, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.OriPaEdit = QtWidgets.QLineEdit(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.OriPaEdit.setFont(font)
        self.OriPaEdit.setMaxLength(20)
        self.OriPaEdit.setObjectName("OriPaEdit")
        self.gridLayout.addWidget(self.OriPaEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.NewPaEdit = QtWidgets.QLineEdit(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.NewPaEdit.setFont(font)
        self.NewPaEdit.setMaxLength(20)
        self.NewPaEdit.setObjectName("NewPaEdit")
        self.gridLayout.addWidget(self.NewPaEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.IDEdit = QtWidgets.QLineEdit(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.IDEdit.setFont(font)
        self.IDEdit.setMaxLength(15)
        self.IDEdit.setReadOnly(True)
        self.IDEdit.setObjectName("IDEdit")
        self.gridLayout.addWidget(self.IDEdit, 0, 1, 1, 1)
        self.NewPaAgainEdit = QtWidgets.QLineEdit(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.NewPaAgainEdit.setFont(font)
        self.NewPaAgainEdit.setMaxLength(20)
        self.NewPaAgainEdit.setObjectName("NewPaAgainEdit")
        self.gridLayout.addWidget(self.NewPaAgainEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.OKButton = QtWidgets.QPushButton(Index_passwordCh)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(24)
        self.OKButton.setFont(font)
        self.OKButton.setObjectName("OKButton")
        self.gridLayout.addWidget(self.OKButton, 4, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 10)
        self.gridLayout.setColumnMinimumWidth(1, 10)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 5)

        self.retranslateUi(Index_passwordCh)
        QtCore.QMetaObject.connectSlotsByName(Index_passwordCh)

    def retranslateUi(self, Index_passwordCh):
        _translate = QtCore.QCoreApplication.translate
        Index_passwordCh.setWindowTitle(_translate("Index_passwordCh", "Dialog"))
        self.label_2.setText(_translate("Index_passwordCh", "<html><head/><body><p>请输入原密码</p></body></html>"))
        self.label.setText(_translate("Index_passwordCh", "<html><head/><body><p>账号名</p></body></html>"))
        self.label_4.setText(_translate("Index_passwordCh", "<html><head/><body><p>请再次输入新密码</p></body></html>"))
        self.label_3.setText(_translate("Index_passwordCh", "<html><head/><body><p>请输入新密码</p></body></html>"))
        self.OKButton.setText(_translate("Index_passwordCh", "确认修改"))
import res_Index_rc
