# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_basicCh.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_basicCh(object):
    def setupUi(self, Index_basicCh):
        Index_basicCh.setObjectName("Index_basicCh")
        Index_basicCh.resize(696, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/38.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index_basicCh.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Index_basicCh)
        self.gridLayout.setContentsMargins(40, -1, 40, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Index_basicCh)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.nameEdit.setFont(font)
        self.nameEdit.setText("")
        self.nameEdit.setMaxLength(5)
        self.nameEdit.setReadOnly(False)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Index_basicCh)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.ageEdit = QtWidgets.QLineEdit(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.ageEdit.setFont(font)
        self.ageEdit.setMaxLength(3)
        self.ageEdit.setReadOnly(False)
        self.ageEdit.setObjectName("ageEdit")
        self.gridLayout.addWidget(self.ageEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Index_basicCh)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.weightEdit = QtWidgets.QLineEdit(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.weightEdit.setFont(font)
        self.weightEdit.setMaxLength(3)
        self.weightEdit.setReadOnly(False)
        self.weightEdit.setObjectName("weightEdit")
        self.gridLayout.addWidget(self.weightEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Index_basicCh)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.heightEdit = QtWidgets.QLineEdit(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.heightEdit.setFont(font)
        self.heightEdit.setMaxLength(3)
        self.heightEdit.setReadOnly(False)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.IDEdit = QtWidgets.QLineEdit(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.IDEdit.setFont(font)
        self.IDEdit.setReadOnly(True)
        self.IDEdit.setObjectName("IDEdit")
        self.gridLayout.addWidget(self.IDEdit, 4, 1, 1, 1)
        self.maleRadio = QtWidgets.QRadioButton(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.maleRadio.setFont(font)
        self.maleRadio.setChecked(True)
        self.maleRadio.setObjectName("maleRadio")
        self.gridLayout.addWidget(self.maleRadio, 5, 0, 1, 1)
        self.femaleRadio = QtWidgets.QRadioButton(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.femaleRadio.setFont(font)
        self.femaleRadio.setChecked(False)
        self.femaleRadio.setObjectName("femaleRadio")
        self.gridLayout.addWidget(self.femaleRadio, 5, 1, 1, 1)
        self.OKButton = QtWidgets.QPushButton(Index_basicCh)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(26)
        self.OKButton.setFont(font)
        self.OKButton.setAutoDefault(False)
        self.OKButton.setObjectName("OKButton")
        self.gridLayout.addWidget(self.OKButton, 6, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 4)
        self.gridLayout.setColumnMinimumWidth(1, 3)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 4)

        self.retranslateUi(Index_basicCh)
        QtCore.QMetaObject.connectSlotsByName(Index_basicCh)

    def retranslateUi(self, Index_basicCh):
        _translate = QtCore.QCoreApplication.translate
        Index_basicCh.setWindowTitle(_translate("Index_basicCh", "Dialog"))
        self.label.setText(_translate("Index_basicCh", "<html><head/><body><p><span style=\" font-size:20pt;\">姓名</span></p></body></html>"))
        self.label_2.setText(_translate("Index_basicCh", "<html><head/><body><p><span style=\" font-size:20pt;\">年龄</span></p></body></html>"))
        self.label_3.setText(_translate("Index_basicCh", "<html><head/><body><p><span style=\" font-size:20pt;\">体重</span></p></body></html>"))
        self.label_4.setText(_translate("Index_basicCh", "<html><head/><body><p><span style=\" font-size:20pt;\">身高</span></p></body></html>"))
        self.label_6.setText(_translate("Index_basicCh", "账号名"))
        self.maleRadio.setText(_translate("Index_basicCh", "男(male)"))
        self.femaleRadio.setText(_translate("Index_basicCh", "女(female)"))
        self.OKButton.setText(_translate("Index_basicCh", "确认修改"))
import res_Index_rc
