# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index(object):
    def setupUi(self, Index):
        Index.setObjectName("Index")
        Index.resize(900, 500)
        Index.setMinimumSize(QtCore.QSize(900, 500))
        Index.setMaximumSize(QtCore.QSize(900, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/123.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(Index)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(210, 10, 681, 421))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 201, 431))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.toolBox.setFont(font)
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox.setObjectName("toolBox")
        self.userPage = QtWidgets.QWidget()
        self.userPage.setGeometry(QtCore.QRect(0, 0, 181, 312))
        self.userPage.setObjectName("userPage")
        self.formLayoutWidget = QtWidgets.QWidget(self.userPage)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 161, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.basicInfoButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.basicInfoButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/food/101.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.basicInfoButton.setIcon(icon1)
        self.basicInfoButton.setObjectName("basicInfoButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.basicInfoButton)
        self.dataChButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dataChButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/food/102.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataChButton.setIcon(icon2)
        self.dataChButton.setObjectName("dataChButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.dataChButton)
        self.passwordButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/food/103.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.passwordButton.setIcon(icon3)
        self.passwordButton.setObjectName("passwordButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.passwordButton)
        self.toolBox.addItem(self.userPage, "")
        self.gasPage = QtWidgets.QWidget()
        self.gasPage.setGeometry(QtCore.QRect(0, 0, 181, 312))
        self.gasPage.setObjectName("gasPage")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.gasPage)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 161, 341))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gasListButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gasListButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/food/104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gasListButton.setIcon(icon4)
        self.gasListButton.setObjectName("gasListButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.gasListButton)
        self.loadGasButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadGasButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/food/105.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadGasButton.setIcon(icon5)
        self.loadGasButton.setObjectName("loadGasButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.loadGasButton)
        self.gasCollectButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gasCollectButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/food/106.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gasCollectButton.setIcon(icon6)
        self.gasCollectButton.setObjectName("gasCollectButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.gasCollectButton)
        self.toolBox.addItem(self.gasPage, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 181, 312))
        self.page.setObjectName("page")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 161, 311))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(11, 11, 11, 11)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.statusListButton = QtWidgets.QPushButton(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusListButton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/food/107.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statusListButton.setIcon(icon7)
        self.statusListButton.setObjectName("statusListButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.statusListButton)
        self.getStatusButton = QtWidgets.QPushButton(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.getStatusButton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/food/108.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getStatusButton.setIcon(icon8)
        self.getStatusButton.setObjectName("getStatusButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.getStatusButton)
        self.toolBox.addItem(self.page, "")
        self.horizontalLayout.addWidget(self.toolBox)
        Index.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Index)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        Index.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Index)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setFloatable(True)
        self.mainToolBar.setObjectName("mainToolBar")
        Index.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Index)
        self.statusBar.setObjectName("statusBar")
        Index.setStatusBar(self.statusBar)
        self.loadGas = QtWidgets.QAction(Index)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/food/194.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadGas.setIcon(icon9)
        self.loadGas.setAutoRepeat(True)
        self.loadGas.setVisible(True)
        self.loadGas.setIconVisibleInMenu(True)
        self.loadGas.setShortcutVisibleInContextMenu(True)
        self.loadGas.setPriority(QtWidgets.QAction.NormalPriority)
        self.loadGas.setObjectName("loadGas")
        self.action = QtWidgets.QAction(Index)
        self.action.setObjectName("action")
        self.openGas = QtWidgets.QAction(Index)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/food/195.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openGas.setIcon(icon10)
        self.openGas.setObjectName("openGas")
        self.menu.addSeparator()
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())
        self.mainToolBar.addAction(self.loadGas)
        self.mainToolBar.addAction(self.openGas)

        self.retranslateUi(Index)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Index)

    def retranslateUi(self, Index):
        _translate = QtCore.QCoreApplication.translate
        Index.setWindowTitle(_translate("Index", "主页面"))
        self.basicInfoButton.setText(_translate("Index", "基本信息"))
        self.dataChButton.setText(_translate("Index", "资料修改"))
        self.passwordButton.setText(_translate("Index", "修改密码"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.userPage), _translate("Index", "用户信息(User)"))
        self.gasListButton.setText(_translate("Index", "查看气体记录"))
        self.loadGasButton.setText(_translate("Index", "导入气体数据"))
        self.gasCollectButton.setText(_translate("Index", "气体采集"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.gasPage), _translate("Index", "气体管理(Gas)"))
        self.statusListButton.setText(_translate("Index", "查看分析记录"))
        self.getStatusButton.setText(_translate("Index", "分析气体数据"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Index", "健康状态(Status)"))
        self.menu.setTitle(_translate("Index", "开始"))
        self.loadGas.setText(_translate("Index", "导入数据"))
        self.loadGas.setShortcut(_translate("Index", "Ctrl+Q"))
        self.action.setText(_translate("Index", "关于"))
        self.openGas.setText(_translate("Index", "气体采集"))
import res_Index_rc
