# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_basicInfo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Index_basicInfo(object):
    def setupUi(self, Index_basicInfo):
        Index_basicInfo.setObjectName("Index_basicInfo")
        Index_basicInfo.resize(642, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Index_basicInfo.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Index_basicInfo)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(40, -1, 40, -1)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.nameEdit = QtWidgets.QLineEdit(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.nameEdit.setFont(font)
        self.nameEdit.setText("")
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 2, 1, 1)
        self.heightEdit = QtWidgets.QLineEdit(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.heightEdit.setFont(font)
        self.heightEdit.setReadOnly(True)
        self.heightEdit.setObjectName("heightEdit")
        self.gridLayout.addWidget(self.heightEdit, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Index_basicInfo)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.weightEdit = QtWidgets.QLineEdit(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.weightEdit.setFont(font)
        self.weightEdit.setReadOnly(True)
        self.weightEdit.setObjectName("weightEdit")
        self.gridLayout.addWidget(self.weightEdit, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Index_basicInfo)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.genderEdit = QtWidgets.QLineEdit(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.genderEdit.setFont(font)
        self.genderEdit.setReadOnly(True)
        self.genderEdit.setObjectName("genderEdit")
        self.gridLayout.addWidget(self.genderEdit, 4, 2, 1, 1)
        self.ageEdit = QtWidgets.QLineEdit(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.ageEdit.setFont(font)
        self.ageEdit.setReadOnly(True)
        self.ageEdit.setObjectName("ageEdit")
        self.gridLayout.addWidget(self.ageEdit, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Index_basicInfo)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Index_basicInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Index_basicInfo)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.IDEdit = QtWidgets.QLineEdit(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.IDEdit.setFont(font)
        self.IDEdit.setReadOnly(True)
        self.IDEdit.setObjectName("IDEdit")
        self.gridLayout.addWidget(self.IDEdit, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Index_basicInfo)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 3)

        self.retranslateUi(Index_basicInfo)
        QtCore.QMetaObject.connectSlotsByName(Index_basicInfo)

    def retranslateUi(self, Index_basicInfo):
        _translate = QtCore.QCoreApplication.translate
        Index_basicInfo.setWindowTitle(_translate("Index_basicInfo", "Form"))
        self.label_2.setText(_translate("Index_basicInfo", "<html><head/><body><p><span style=\" font-size:20pt;\">年龄</span></p></body></html>"))
        self.label_5.setText(_translate("Index_basicInfo", "<html><head/><body><p><span style=\" font-size:20pt;\">性别</span></p></body></html>"))
        self.label_4.setText(_translate("Index_basicInfo", "<html><head/><body><p><span style=\" font-size:20pt;\">身高</span></p></body></html>"))
        self.label_3.setText(_translate("Index_basicInfo", "<html><head/><body><p><span style=\" font-size:20pt;\">体重</span></p></body></html>"))
        self.label.setText(_translate("Index_basicInfo", "<html><head/><body><p><span style=\" font-size:20pt;\">姓名</span></p></body></html>"))
        self.label_6.setText(_translate("Index_basicInfo", "账号ID"))
import res_Index_rc
