# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(750, 500)
        LoginWidget.setMinimumSize(QtCore.QSize(750, 500))
        LoginWidget.setMaximumSize(QtCore.QSize(750, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/food/67.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWidget.setWindowIcon(icon)
        self.Button_left = QtWidgets.QPushButton(LoginWidget)
        self.Button_left.setGeometry(QtCore.QRect(250, 320, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.Button_left.setFont(font)
        self.Button_left.setAutoFillBackground(False)
        self.Button_left.setObjectName("Button_left")
        self.Button_right = QtWidgets.QPushButton(LoginWidget)
        self.Button_right.setGeometry(QtCore.QRect(380, 320, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.Button_right.setFont(font)
        self.Button_right.setAutoFillBackground(False)
        self.Button_right.setObjectName("Button_right")
        self.ID_Edit = QtWidgets.QLineEdit(LoginWidget)
        self.ID_Edit.setGeometry(QtCore.QRect(330, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ID_Edit.setFont(font)
        self.ID_Edit.setMaxLength(20)
        self.ID_Edit.setObjectName("ID_Edit")
        self.Password_Edit = QtWidgets.QLineEdit(LoginWidget)
        self.Password_Edit.setGeometry(QtCore.QRect(330, 200, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Password_Edit.setFont(font)
        self.Password_Edit.setMaxLength(20)
        self.Password_Edit.setCursorPosition(9)
        self.Password_Edit.setDragEnabled(False)
        self.Password_Edit.setObjectName("Password_Edit")
        self.PAagin_Edit = QtWidgets.QLineEdit(LoginWidget)
        self.PAagin_Edit.setGeometry(QtCore.QRect(330, 240, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.PAagin_Edit.setFont(font)
        self.PAagin_Edit.setText("")
        self.PAagin_Edit.setMaxLength(20)
        self.PAagin_Edit.setObjectName("PAagin_Edit")
        self.Mobile_Edit = QtWidgets.QLineEdit(LoginWidget)
        self.Mobile_Edit.setGeometry(QtCore.QRect(330, 280, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Mobile_Edit.setFont(font)
        self.Mobile_Edit.setText("")
        self.Mobile_Edit.setMaxLength(12)
        self.Mobile_Edit.setObjectName("Mobile_Edit")
        self.ID_label = QtWidgets.QLabel(LoginWidget)
        self.ID_label.setGeometry(QtCore.QRect(200, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.ID_label.setFont(font)
        self.ID_label.setObjectName("ID_label")
        self.Password_label = QtWidgets.QLabel(LoginWidget)
        self.Password_label.setGeometry(QtCore.QRect(200, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Password_label.setFont(font)
        self.Password_label.setObjectName("Password_label")
        self.Mobile_label = QtWidgets.QLabel(LoginWidget)
        self.Mobile_label.setGeometry(QtCore.QRect(200, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Mobile_label.setFont(font)
        self.Mobile_label.setObjectName("Mobile_label")
        self.PAagin_label_CN = QtWidgets.QLabel(LoginWidget)
        self.PAagin_label_CN.setGeometry(QtCore.QRect(200, 240, 101, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.PAagin_label_CN.setFont(font)
        self.PAagin_label_CN.setObjectName("PAagin_label_CN")
        self.PAagin_label_EN = QtWidgets.QLabel(LoginWidget)
        self.PAagin_label_EN.setGeometry(QtCore.QRect(190, 260, 131, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.PAagin_label_EN.setFont(font)
        self.PAagin_label_EN.setObjectName("PAagin_label_EN")
        self.Notice_label = QtWidgets.QLabel(LoginWidget)
        self.Notice_label.setGeometry(QtCore.QRect(270, 360, 211, 20))
        self.Notice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Notice_label.setObjectName("Notice_label")

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "登录"))
        self.Button_left.setText(_translate("LoginWidget", "登 录"))
        self.Button_right.setText(_translate("LoginWidget", "注 册"))
        #self.ID_Edit.setText(_translate("LoginWidget", "root"))
        self.ID_Edit.setPlaceholderText(_translate("LoginWidget", "6~15位,只能包含数字和字母"))
        #self.Password_Edit.setText(_translate("LoginWidget", "wyz007520"))
        self.Password_Edit.setPlaceholderText(_translate("LoginWidget", "6~20位,只能包含数字和字母"))
        self.PAagin_Edit.setPlaceholderText(_translate("LoginWidget", "6~20位,只能包含数字和字母"))
        self.ID_label.setText(_translate("LoginWidget", "账号(ID)"))
        self.Password_label.setText(_translate("LoginWidget", "密码(Password)"))
        self.Mobile_label.setText(_translate("LoginWidget", "电话(Mobile)"))
        self.PAagin_label_CN.setText(_translate("LoginWidget", "再次输入密码"))
        self.PAagin_label_EN.setText(_translate("LoginWidget", "(Password Again)"))
        self.Notice_label.setText(_translate("LoginWidget", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">TextLabel</span></p></body></html>"))
import res_Login_rc
